/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Login information for OBS Websocket, used to communicate with and remotely control OBS Studio.
 */
export interface Websocket {
	ip: string;
	port: number;
	password: string;
	status: 'connected' | 'connecting' | 'disconnected' | 'error';
}
